name: '  (FAASR INVOKE)'

on:
  workflow_dispatch:
    inputs:
      workflow_file:
        description: 'Workflow JSON file name'
        required: true
        type: string

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 requests jsonschema cryptography
          pip install FaaSr_py

      - name: Install OpenWhisk CLI
        run: |
          # Download and install the latest OpenWhisk CLI for Linux
          wget -q https://github.com/apache/openwhisk-cli/releases/download/1.2.0/OpenWhisk_CLI-1.2.0-linux-amd64.tgz
          tar -xzf OpenWhisk_CLI-1.2.0-linux-amd64.tgz
          sudo mv wsk /usr/local/bin/wsk
          sudo chmod +x /usr/local/bin/wsk
          # Verify installation
          wsk --help

      - name: Configure OpenWhisk CLI
        env:
          OW_API_KEY: ${{ secrets.OW_API_KEY }}
        run: |
          # Set environment variable to handle certificate issues
          echo "GODEBUG=x509ignoreCN=0" >> $GITHUB_ENV
          # Note: All wsk properties (API host, auth, insecure) will be set by the Python script

      - name: Trigger function
        env:
          OW_APIkey: ${{ secrets.OW_APIkey }}
          AWS_AccessKey: ${{ secrets.AWS_AccessKey }}
          AWS_SecretKey: ${{ secrets.AWS_SecretKey }}
          GCP_SecretKey: ${{ secrets.GCP_SecretKey }}	
          SLURM_Token: ${{ secrets.SLURM_Token }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          python scripts/invoke_workflow.py --workflow-file ${{ github.event.inputs.workflow_file }} 
